<div class="row">

	<div class="columns medium-6 small-12 right-space">
		<h2>Locations</h2>
		<div class="text-center"><a href="locations.php"><img src="img/map-s.jpg" alt="Roadmaster Locations" title="Roadmaster Locations"></a></div>
		<br>
		<div data-id="VTDwZXttFO" class="livechat_button text-center hide-for-small-only"></div>
	</div>

<div class="columns medium-6 small-12">
<h2>Social Media Hub</h2>
<iframe class="mixedContent" src="http://roadmaster.uberflip.com/hubsFront/embedGrid?w=350&h=350&cols=1&rows=1&trans=slideLeft&label=Enter%20our%20Social%20Hub&open=_top&interval=2&website=roadmaster.com%2Fsocial" scroll="none" border="0" frameborder="0" width="350" height="350" style="height:350px;width:350px;border:0;margin:0;padding:0;overflow:none;background:transparent">&nbsp;</iframe>
<br><br>
</div>

</div>

