	<ul class="footerlink">
		<li><a href="contact.php">Apply Now</a></li>
		<li><a class="left-off-canvas-toggle" href="#">Main Menu</a></li>
		<li><a href="cdl_training.php">CDL Training</a></li>
		<li><a href="locations.php">Locations</a></li>
		<li><a href="truck_school_admissions.php">Admissions</a></li>
		<li><a href="truck_school_finance.php">Finance</a></li>
		<li><a href="blog/index.php" target="_blank">Blog</a></li>
	</ul>