	   	  <!-- First Footer Column -->
	   	  <div class="small-12 large-4 medium-6 small-12 columns">
		   		<!-- Event Manager Listing -->
				<h4>Upcoming Events</h4>
				<!-- Put an include for this file when live "mm/mm-framed-hp.php"-->
				<!-- Event Manager Listings End -->
	   		</div>
   	   		
   	   		<!-- Second Footer Column -->
	   	<div class="hide-for-medium-only small-12 large-4 columns">
		   	<section>
		   	<h4>Latest from our Blog</h4>
<div class="feedgrabbr_widget" id="fgid_9879fe0fbee625d006c0c0a60"></div>
<script> if (typeof(fg_widgets)==="undefined") fg_widgets = new Array();fg_widgets.push("fgid_9879fe0fbee625d006c0c0a60");</script>
<script src='http://www.feedgrabbr.com/widget/fgwidget.js'></script>

	   		</section>
	   	</div>
	   		
	   		<!-- Third Footer Column -->
	   	<div class="large-4 medium-6 small-12 columns">
		   		<section class="text-center">	   			
	   				<a href="index.php"><img id="footerLogo" src="../img/logos/roadmaster-logo.png"></a>
		   			<?php include("../inc/social.inc"); ?>
		   			<h2 class="text-center">1-800-831-1300</h2>
		   			<br>
		   			<div class="text-center hide-for-small-only"><a href="contact.php"><img src="../img/applyNow-white.png" border="0"></a></div>	
		   			
		   		 </section>
	   	</div>