	   	  <!-- First Footer Column -->
	   	  <div class="small-12 large-4 medium-6 small-12 columns">
	   	  	 <ul class="medium-block-grid-2 text-center hide-for-small">
				  <li><a href="http://www.caltrux.org" target="_blank"><img src="http://www.roadmaster.com/img/logos/footer-tca.jpg" alt="Truckload Carriers Association" /></a></li>
				  <li><a href="http://www.trucking.org" target="_blank"><img src="http://www.roadmaster.com/img/logos/footer-ata.jpg" alt="American TruckingAssociation" /></a></li>
		  	</ul>
		  	<ul class="medium-block-grid-1 text-center hide-for-small">
		  		 <li><a href="http://cvta.org" target="_blank"><img src="http://www.roadmaster.com/img/logos/footer-CVTA.jpg" alt="Commercial Vehicle Training Association" /></a></li>
		  	</ul>
		  	
		  	<ul class="small-block-grid-3 text-center show-for-small">
				  <li><a href="http://www.caltrux.org" target="_blank"><img src="http://www.roadmaster.com/img/logos/footer-tca.jpg" alt="Truckload Carriers Association" /></a></li>
				  <li><a href="http://www.trucking.org" target="_blank"><img src="http://www.roadmaster.com/img/logos/footer-ata.jpg" alt="American TruckingAssociation" /></a></li>
				  <li><a href="http://cvta.org" target="_blank"><img src="http://www.roadmaster.com/img/logos/footer-CVTA.jpg" alt="Commercial Vehicle Training Association" /></a></li>
		  	</ul>
	   		</div>
   	   		
   	   		<!-- Second Footer Column -->
	   	<div class="hide-for-medium-only small-12 large-4 columns">
		   	<section>
		   	<h4>Latest from our Blog</h4>
<div class="feedgrabbr_widget" id="fgid_9879fe0fbee625d006c0c0a60"></div>
<script> if (typeof(fg_widgets)==="undefined") fg_widgets = new Array();fg_widgets.push("fgid_9879fe0fbee625d006c0c0a60");</script>
<script src='http://www.feedgrabbr.com/widget/fgwidget.js'></script>

	   		</section>
	   	</div>
	   		
	   		<!-- Third Footer Column -->
	   	<div class="large-4 medium-6 small-12 columns">
		   		<section class="text-center">	   			
	   				<a href="index.php"><img id="footerLogo" src="http://www.roadmaster.com/img/logos/roadmaster-logo.png"></a>
		   			<?php include("../inc/social.inc"); ?>
		   			<h2 class="text-center">1-800-831-1300</h2>
		   			<br>
		   			<div class="text-center hide-for-small-only"><a href="contact.php"><img src="http://www.roadmaster.com/img/applyNow-white.png" border="0"></a></div>	
		   			
		   		 </section>
	   	</div>