  <!-- Live Chat -->
  	<script type="text/javascript">
	var __lc = {};
	__lc.license = 4004091;
	
	(function() {
		var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
		lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
	})();
	</script>
  <!-- END Live Chat -->
  
  <!-- Google Analytics Tracking Code-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-317493-11', 'auto');
  ga('send', 'pageview');

</script>
<!-- END Google Analytics Tracking Code-->

<!-- Facebook Remarketing Code -->
<script>(function() {
  var _fbq = window._fbq || (window._fbq = []);
  if (!_fbq.loaded) {
    var fbds = document.createElement('script');
    fbds.async = true;
    fbds.src = '//connect.facebook.net/en_US/fbds.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(fbds, s);
    _fbq.loaded = true;
  }
  _fbq.push(['addPixelId', '1549939651885554']);
})();
window._fbq = window._fbq || [];
window._fbq.push(['track', 'PixelInitialized', {}]);
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/tr?id=1549939651885554&amp;ev=PixelInitialized" /></noscript>
<!-- END Facebook Remarketing Code -->

  
  
<!-- Google Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1072628500;
var google_conversion_label = "VWVyCOKimgQQlIa8_wM";
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/1072628500/?value=0&amp;label=VWVyCOKimgQQlIa8_wM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<!-- END Remarketing Code-->

<!-- Hello Bar-->
<!--<script src="//my.hellobar.com/72dbbb4c643b0a7e2ee1d0a62d0fc6415c6c3b31.js" type="text/javascript" charset="utf-8" async="async"></script>-->
<!-- END Hello Bar-->

    <!-- End Scripts -->
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="http://cdn.foundation5.zurb.com/foundation.js"></script>
	<script src="/js/foundation/foundation.abide.js"></script>

    
  <script>
    $(document).foundation();
	$(".off-canvas-submenu").hide();
	$(".off-canvas-submenu-call").click(function() {
	var icon = $(this).parent().next(".off-canvas-submenu").is(':visible') ? '+' : '-';
	$(this).parent().next(".off-canvas-submenu").slideToggle('fast');
	$(this).find("span").text(icon);
});
</script>


<!-- Adroll Pixel-->
<script type="text/javascript">
    adroll_adv_id = "TGKADP3NJNGP7CQFINLBGV";
    adroll_pix_id = "ROLU64DDKZAUHBLAQVABYT";
    /* OPTIONAL: provide email to improve user identification */
    /* adroll_email = "username@example.com"; */
    (function () {
        var _onload = function(){
            if (document.readyState && !/loaded|complete/.test(document.readyState)){setTimeout(_onload, 10);return}
            if (!window.__adroll_loaded){__adroll_loaded=true;setTimeout(_onload, 50);return}
            var scr = document.createElement("script");
            var host = (("https:" == document.location.protocol) ? "https://s.adroll.com" : "http://a.adroll.com");
            scr.setAttribute('async', 'true');
            scr.type = "text/javascript";
            scr.src = host + "/j/roundtrip.js";
            ((document.getElementsByTagName('head') || [null])[0] ||
                document.getElementsByTagName('script')[0].parentNode).appendChild(scr);
        };
        if (window.addEventListener) {window.addEventListener('load', _onload, false);}
        else {window.attachEvent('onload', _onload)}
    }());
</script>
<!-- END Adroll Pixel-->
    