<ul class="off-canvas-list">
    <!-- Include Left Nav -->
     <li><a href="/index.php">Home Page</a></li>
    <li><label>CDL Training Information</label></li>
    <li><a href="/cdl_training.php">CDL Training</a></li>
    <li><a href="/cdl_training_class-a.php">What is a CDL License?</a></li>
    <li><a href="/cdl-requirements.php">CDL License Requirements</a></li>
    <!--<li><a href="/free-and-paid-cdl-training.php">Free & Paid CDL Training</a></li>-->
         <li><a href="#" class="off-canvas-submenu-call">How to Get Your CDL (by state)<span class="right"> + </span></a></a></li>
    						 <ul class="off-canvas-submenu no-bullets">					
								<li><a href="/how-to-get-your-cdl-license-in-arkansas.php">How to get your CDL in Arkansas</a></li>
								<li><a href="/how-to-get-your-cdl-license-in-california.php">How to get your CDL in California</a></li>
								<!--<li><a href="/how-to-get-your-cdl-license-in-georgia.php">How to get your CDL in Georgia</a></li>-->
								<li><a href="/how-to-get-your-cdl-license-in-florida.php">How to get your CDL in Florida</a></li>
								<li><a href="/how-to-get-your-cdl-license-in-north-carolina.php">How to get your CDL in N. Carolina</a></li>
								<li><a href="/how-to-get-your-cdl-license-in-ohio.php">How to get your CDL in Ohio</a></li>
								<li><a href="/how-to-get-your-cdl-license-in-oklahoma.php">How to get your CDL in Oklahoma</a></li>
								<li><a href="/how-to-get-your-cdl-license-in-pennsylvania.php">How to get your CDL in Pennsylvania</a></li>
								<li><a href="/how-to-get-your-cdl-license-in-tennessee.php">How to get your CDL in Tennessee</a></li>
								<li><a href="/how-to-get-your-cdl-license-in-texas.php">How to get your CDL in Texas</a></li>
							</ul>
     <li><a href="/truck-driver-shortage.php">Truck Driver Shortage</a></li>
    <li><a href="/how-much-do-truck-drivers-make.php">Truck Driver Pay</a></li>
    <li><a href="/trucking_benefits.php">Truck Driving Benefits</a></li>
    <li><a href="/what-is-truck-driving-school-like.php">What is Truck Driving School like?</a></li>
    <li><a href="/carrier-choice.php">Choice of Employers</a></li>
    <li><a href="/veteran-cdl-training.php">Veteran's Training</a></li>
     <li><a href="/refresher_courses.php">CDL Refresher Course</a></li>
    
     <li><label>Going To School</label></li>
     <li><a href="/truck_school_locations.php">Locations</a></li>
    <!--<li><a href="/process.php">How to Apply</a></li>-->
     <li><a href="/truck_school_admissions.php">Admissions</a></li>
    <li><a href="/truck_school_finance.php">Finance</a></li>
     <!--<li><a href="/truck-driving-school-cost.php">Truck Driving Cost</a></li>-->
    <li><a href="/tuition-reimbursement.php">Tuition Reimbursement</a></li>
    <li><a href="/nights-weekend-cdl-training.php">Night & Weekend Training</a></li>
    <li><a href="/graduation.php">Graduation</a></li>
    <li><a href="/job-placement.php">Job Placement</a></li>
    <li><a href="/contact.php">Apply Now</a></li>
    
     <li><label>Roadmaster Information</label></li>
    <li><a href="/contact.php">Contact Us</a></li>
    <li><a href="/feedback">Complaints and Concerns</a></li>
    <li><a href="/truck_school_locations.php">Locations</a></li>
    <li><a href="/roadmaster_careers.php">Roadmaster Job Openings</a></li>
    <li><a href="/trucking_about_Roadmaster.php">About Roadmaster</a></li>
    <li><a href="/trucking_about_Roadmaster-history.php">Roadmaster History</a></li>
    <li><a href="/RoadmasterDriversSchool_Safety.php">Training Safety</a></li>
    <li><a href="/get_hired.php">Recruiters</a></li>
</ul>