<ul class="off-canvas-list">
    <!-- Include Left Nav -->
    <li><label>Main Menu</label></li>
    <li><a href="/index.php">Home Page</a></li>
    <li><a href="/cdl_training.php">CDL Training</a></li>
    <li><a href="/cdl_training_class-a.php">What is a CDL License?</a></li>
     <li><a href="/help">CDL Training Help Center</a></li>
    <li><a href="/trucking_benefits.php">Truck Driving Benefits</a></li>
    <li><a href="/what-is-truck-driving-school-like.php">What is Truck Driving School like?</a></li>
    <li><a href="/truck_school_admissions.php">Admissions</a></li>
    <li><a href="/truck_school_finance.php">Finance</a></li>
    <li><a href="/truck_school_locations.php">Locations</a></li>
    <li><a href="/refresher_courses.php">CDL Refresher Course</a></li>
    <li><a href="/veteran-cdl-training.php">Veteran's Training</a></li>
	<li><a href="/veteran-cdl-apply.php">Veteran CDL Application</a></li>
    <li><a href="/event-listings.php">Event Listings</a></li>
	<li><a href="/blog" target="_blank">Blog</a></li>
	<li><a href="http://roadmaster.deco-apparel.com" target="_blank">Roadmaster Store</a></li>
    <li><a href="/social">Social Media Hub</a></li>
     <li><a href="/trucking_resources.php">Trucking Resources</a></li>
     
     <li><label>Roadmaster Information</label></li>
    <li><a href="/contact.php">Contact Us</a></li>
    <li><a href="/feedback">Complaints and Concerns</a></li>
    <li><a href="/roadmaster_careers.php">Roadmaster Job Openings</a></li>
    <li><a href="/trucking_about_Roadmaster.php">About Roadmaster</a></li>
    <li><a href="/trucking_about_Roadmaster-history.php">Roadmaster History</a></li>
    <li><a href="/RoadmasterDriversSchool_Safety.php">Roadmaster Safety</a></li>
    <li><a href="/get_hired.php">Recruiters</a></li>
</ul>