<ul id="locations-nav">
	<li><a href="/truck_school_WESTMEMPHIS.php">West Memphis, AR</a></li>
	<li><a href="/truck_school_fontanaCalifornia.php">Fontana, CA</a></li>
	<li><a href="/truck_school_JACKSONVILLE.php">Jacksonville, FL</a></li>
	<li><a href="/truck_school_ORLANDO.php">Orlando, FL</a></li>
	<li><a href="/truck_school_TAMPA.php">Tampa, FL</a></li>
	<li><a href="/truck_school_northcarolina.php">Dunn, NC</a></li>
	<li><a href="/truck_school_OHIO.php">Columbus, OH</a></li>
	<li><a href="/truck_school_Tulsa.php">Tulsa, OK</a></li>
	<li><a href="/truck_school_Bethlehem_Pennsylvania.php">Bethlehem, PA</a></li>
	<li><a href="/truck_school_Memphis_Tennessee.php">Memphis, TN</a></li>
	<li><a href="/truck_school_SANANTONIO.php">San Antonio, TX</a></li>
</ul>

<div class="text-center">
<a href="#formJump"><img src="/img/applyNow.png" border="0"></a>
</div>