<table id="locationsTable" width="100%">
  <tbody>
    <tr>
      <td><a href="/truck_school_WESTMEMPHIS.php">West Memphis, AR</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_WESTMEMPHIS.php">2800 East North Service Road | West Memphis, AR 72301</a></td>
      <td><a href="/truck_school_WESTMEMPHIS.php">(870) 400-4090</a></td>
      <td class="show-for-large-up"><a href="/truck_school_WESTMEMPHIS.php">School Website</a></td>
    </tr>
        <tr>
      <td><a href="/truck_school_fontanaCalifornia.php">Fontana, CA</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_fontanaCalifornia.php">10251 Calabash Ave | Fontana,CA 92335</a></td>
      <td><a href="/truck_school_fontanaCalifornia.php">(909) 202-4270</a></td>
      <td class="show-for-large-up"><a href="/truck_school_fontanaCalifornia.php">School Website</a></td>
    </tr>
        <tr>
      <td><a href="/truck_school_JACKSONVILLE.php">Jacksonville, FL</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_JACKSONVILLE.php">1409 Pickettville Road | Jacksonville, Florida 32220</a></td>
      <td><a href="/truck_school_JACKSONVILLE.php">(904) 783-3333</a></td>
      <td class="show-for-large-up"><a href="/truck_school_JACKSONVILLE.php">School Website</a></td>
    </tr>
        <tr>
      <td><a href="/truck_school_ORLANDO.php">Orlando, FL</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_ORLANDO.php">6000 Cinderlane Parkway | Orlando, Florida 32810</a></td>
      <td><a href="/truck_school_ORLANDO.php">(407) 532-3619</a></td>
      <td class="show-for-large-up"><a href="/truck_school_ORLANDO.php">School Website</a></td>
    </tr>
        <tr>
      <td><a href="/truck_school_TAMPA.php">Tampa, FL</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_TAMPA.php">5025 Orient Road | Tampa, FL 33610</a></td>
      <td><a href="/truck_school_TAMPA.php">(813) 626-2400</a></td>
      <td class="show-for-large-up"><a href="/truck_school_TAMPA.php">School Website</a></td>
    </tr>
        <tr>
      <td><a href="/truck_school_INDIANA.php">Indianapolis, IN</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_INDIANA.php">3016 Bluff Road | Indianapolis, IN 46217</a></td>
      <td><a href="/truck_school_INDIANA.php">(317) 783-7483</a></td>
      <td class="show-for-large-up"><a href="/truck_school_INDIANA.php">School Website</a></td>
    </tr>
        <tr>
      <td><a href="/truck_school_northcarolina.php">Dunn, NC</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_northcarolina.php">1111 South Clinton Avenue | Dunn, North Carolina 28335</a></td>
      <td><a href="/truck_school_northcarolina.php">(910) 891-1344</a></td>
      <td class="show-for-large-up"><a href="/truck_school_northcarolina.php">School Website</a></td>
    </tr>
        <tr>
      <td><a href="/truck_school_OHIO.php">Columbus, OH</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_OHIO.php">4060 Perimeter Drive | Columbus, OH 43228</a></td>
      <td><a href="/truck_school_OHIO.php">(614) 351-1748</a></td>
      <td class="show-for-large-up"><a href="/truck_school_OHIO.php">School Website</a></td>
    </tr>
        <tr>
      <td><a href="/truck_school_Tulsa.php">Tulsa, OK</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_Tulsa.php">2215 N Sheridan Rd. | Tulsa, OK 74115</a></td>
      <td><a href="/truck_school_Tulsa.php">(918) 834-6221</a></td>
      <td class="show-for-large-up"><a href="/truck_school_Tulsa.php">School Website</a></td>
    </tr>
    <tr>
      <td><a href="/truck_school_Bethlehem_Pennsylvania.php">Bethlehem, PA</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_Bethlehem_Pennsylvania.php">4219 Fritch Drive | Bethlehem, PA 18020</a></td>
      <td><a href="/truck_school_Bethlehem_Pennsylvania.php">(610) 365-1037</a></td>
      <td class="show-for-large-up"><a href="/truck_school_Bethlehem_Pennsylvania.php">School Website</a></td>
    </tr>
        <tr>
      <td><a href="/truck_school_Memphis_Tennessee.php">Memphis, TN</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_Memphis_Tennessee.php">8050 Singleton Avenue | Memphis, TN 38053</a></td>
      <td><a href="/truck_school_Memphis_Tennessee.php">(901) 873-3742</a></td>
      <td class="show-for-large-up"><a href="/truck_school_Memphis_Tennessee.php">School Website</a></td>
    </tr>
             <tr>
      <td><a href="/truck_school_SANANTONIO.php">San Antonio, TX</a></td>
      <td class="hide-for-small-only"><a href="/truck_school_SANANTONIO.php">927 Eddie Road | San Antonio, TX 78219</a></td>
      <td><a href="/truck_school_SANANTONIO.php">(210) 648-8600</a></td>
      <td class="show-for-large-up"><a href="/truck_school_SANANTONIO.php">School Website</a></td>
    </tr>

  </tbody>
</table>