 <section class="hide-for-medium-up middle tab-bar-section">
	   <a href="index.php"><img src="/img/logo-trans.gif" alt="Roadmaster Truck Driving School Logo"></a>
	   <a class="hide-for-small-only" href="tel:+1-800-831-1303">1-800-831-1303</a>
  </section>

      <section class="hide-for-small-only middle tab-bar-section text-right">
	       <a href="index.php"><img style="float:left;" src="/img/logo-trans.gif" alt="Roadmaster Truck Driving School Logo"></a>
			<a style="color:red;" href="contact.php">Apply Now</a> |
			<a class="left-off-canvas-toggle" href="#">Main Menu</a> |
			<a href="cdl_training.php">CDL Training</a> |
			<a href="truck_school_finance.php">Cost & Financing</a> |
			<a href="truck_school_locations.php">Locations</a> |
			<a href="blog/index.php" target="_blank">Blog</a>
			| <div data-id="VViyr0BhEGm" class="livechat_button"></div>
      </section>