<div class="row" id="quickNav">
	<div class="show-for-small-only small-12">
		<table width="100%">
		<tr><td colspan="2" class="header-row">Quick Links</td></tr>
		<tr>
			<td><a href="index.php">Home Page</a></td>
			<td><a href="truck_school_locations.php">Locations</a></td>
		</tr>
		<tr>
			<td><a href="cdl_training.php">CDL Training</a></td>
			<td><a href="truck_school_finance.php">Financing</a></td>
		</tr>
		<tr>
			<td><a href="truck_school_admissions.php">Admissions</a></td>
			<td><a href="contact.php">Apply Now</a></td>
		</tr>
				<tr>
			<td><a href="/help">CDL Help Center</a></td>
			<td><a href="/blog">Blog</a></td>
		</tr>
		
		<tr><td colspan="2">
			<?php include("inc/social.inc"); ?>
		</td></tr>
		<tr><td colspan="2">
				<div data-id="VTDwZXttFO" class="livechat_button text-center"></div>
		</td></tr>
		</table>
			<div class="text-center"><a href="#topJump">Return to Top</a><br><br></div>
	</div>
</div>