<ul class="off-canvas-list">
    <!-- Include Left Nav -->
    <li><label>Locations</label></li>
    <li><a href="/truck_school_locations.php">All Locations</a></li>
    <li><a href="/truck_school_WESTMEMPHIS.php">West Memphis, AR</a></li>
	<li><a href="/truck_school_fontanaCalifornia.php">Fontana, CA</a></li>
	<li><a href="/truck_school_JACKSONVILLE.php">Jacksonville, FL</a></li>
	<li><a href="/truck_school_ORLANDO.php">Orlando, FL</a></li>
	<li><a href="/truck_school_TAMPA.php">Tampa, FL</a></li>
	<li><a href="/truck_school_northcarolina.php">Dunn, NC</a></li>
	<li><a href="/truck_school_OHIO.php">Columbus, OH</a></li>
	<li><a href="/truck_school_Tulsa.php">Tulsa, OK</a></li>
	<li><a href="/truck_school_bethlehem_pennsylvania.php">Bethlehem, PA</a></li>
	<li><a href="/truck_school_Memphis_Tennessee.php">Memphis, TN</a></li>
	<li><a href="/truck_school_SANANTONIO.php">San Antonio, TX</a></li>
	
    <li><label>Helpful Resources</label></li>
    <li><a href="/help">CDL Training Help Center</a></li>
	<li><a href="/blog" target="_blank">Blog</a></li>
	<li><a href="http://roadmaster.deco-apparel.com" target="_blank">Roadmaster Store</a></li>
    <li><a href="/social">Social Media Hub</a></li>
    <li><a href="/trucking_resources.php">Trucking Resources</a></li>
    </ul>