 <ul class="medium-block-grid-8 large-block-grid-8 small-block-grid-4 text-center" id="social">
	<li><a href="facebook.php"><i class="step fi-social-facebook" alt="Facebook" title="Facebook"></i></a></li>
	<li><a href="twitter.php"><i class="step fi-social-twitter" title="Twitter" alt="Twitter"></i></a></li>
	<li><a href="youtube.php"><i class="step fi-social-youtube" alt="YouTube" title="YouTube"></i></a></li>
	<li><a href="https://plus.google.com/113619994409207860357/posts" target="_blank"><i class="step fi-social-google-plus" alt="Google Plus" title="Google Plus"></i></a></li>
	<li><a href="http://www.pinterest.com/roadmastercdl/" target="_blank"><i class="step fi-social-pinterest" alt="Pinterest" title="Pinterest"></i></a></li>
	<li><a href="instagram.php"><i class="step fi-social-instagram" alt="Instagram" title="Instagram"></i></a></li>
	<li><a href="http://www.roadmaster.com/blog" target="_blank"><i class="step fi-rss" alt="Roadmaster Blog" title="Roadmaster Blog"></i></a></li>
		<li><a href="http://www.roadmaster.com/help" target="_blank"><i class="step fi-lightbulb" alt="CDL Help Center" title="CDL Help Center"></i></a></li>
</ul>